### ISSUE TITLE
How can i use this binary on mac? 

### ISSUE THREAD

**Issue by g-dumas** [toch/intercom-export#2] opened 2017-03-23 10:31 UTC
Hello, 
I run the command `docker-compose run compile` on mac. 
And I cannot find the `./mruby/build/host/bin/intercom-export`
could you send me the exact process, I could update the documentation.

**Comment by toch** [comment] 2017-03-26 19:53
Hi @guillaumebadin 

Thanks for spotting that. I've just pushed a change enabling the build for major platforms. There you should have a binary `intercom-export` in `./mruby/build/x86_64-apple-darwin14/bin/` after having run `docker-compose run compile`. Do you find it?

FYI, you can disable the building for other platforms into the `build_config.rb` file.

**Comment by toch** [comment] 2017-10-02 08:06
I'm closing this issue. If the issue is not fixed for you @guillaumebadin, tell me.

**Closed as completed by toch** 2017-10-02 08:06 UTC
